// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw28qlBXBlKdG_JvZnEcC74MNesI3P4EY',
    appId: '1:1079862973567:web:905d283486f0deafd21b4a',
    messagingSenderId: '1079862973567',
    projectId: 'mygardenstore-158cb',
    authDomain: 'mygardenstore-158cb.firebaseapp.com',
    storageBucket: 'mygardenstore-158cb.appspot.com',
    measurementId: 'G-SEM55HBFB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDek3dwIUNGYDsM7zr0wTdXaSVTR3OsJDc',
    appId: '1:1079862973567:android:dd899fa7d7116e06d21b4a',
    messagingSenderId: '1079862973567',
    projectId: 'mygardenstore-158cb',
    storageBucket: 'mygardenstore-158cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgYhFJU08xuqXPuL5ACUZPnSWKC7z4Pfc',
    appId: '1:1079862973567:ios:b28f56ac4102fc39d21b4a',
    messagingSenderId: '1079862973567',
    projectId: 'mygardenstore-158cb',
    storageBucket: 'mygardenstore-158cb.appspot.com',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgYhFJU08xuqXPuL5ACUZPnSWKC7z4Pfc',
    appId: '1:1079862973567:ios:a0ec5e9bf59547cad21b4a',
    messagingSenderId: '1079862973567',
    projectId: 'mygardenstore-158cb',
    storageBucket: 'mygardenstore-158cb.appspot.com',
    iosBundleId: 'com.example.cwtEcommerceApp.RunnerTests',
  );
}
